name: generate-pdf
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: git add cv.pdf
      - run: git commit -m "github actions generated PDF on `date +%Y-%m-%dT%H:%M:%S`"
      - run: git fetch origin master
      - run: git push origin HEAD:master